### ISSUE TITLE
On error, try to reconnect

### ISSUE THREAD

**Issue by hscheewel** [patrickjane/ut-radio#3]
Hi! Many thanks for your app! I'm using it several times every day.

I made one observation while using it: Due to my bad wifi connection, the radio stream interrupts very often and produces an error message. Each time that happens, I have to manually reconnect. Would it be possible to automatically attempt reconnections to the radio stream when an error occurs? That would be great!

**Comment by patrickjane** [comment]
Thanks for the hint. Gonna check it out in a couple of days. Maybe this can be changed so it automatically tries to reconnect.

**Comment by patrickjane** [comment]
I just pushed an update which contains improved re-connection functionality. However, there will still be cases where it will not automatically resume playing.
For example, in my tests, when completely cutting wifi for a minute or so, I was not able to resume the stream after wifi went on again. This might be due to restrictions in QT's audioplayer; calling corresponding stop/play functions just did not have any effect. This is, unfortunately, beyond of what I can do.

For short interruptions, I hope though, that the situation improved.

3aa772898e70db764aad0a2bae2884ca8b8c2578
