### ISSUE TITLE
Paysage mode

### ISSUE THREAD

**Issue by gbdomubpkm** [patrickjane/ut-radio#8]
Paysage mode doesn't work currently. Will be useful so as to see a long song title by the scrolling of sound indicator menu.

**Comment by patrickjane** [comment]
Landscape mode is disabled on purpose, since I didn't want to hassle with making the UI nice for landscape more too. Also I think portrait mode better fits the application.

I will take a look at this and make a scrolling title bar, which allows to show longer text.

For the time being, you can manually allow landscape mode, by editing `~/.local/share/applications/radio.s710_Radio_1.3.1.desktop` and removing the line `X-Ubuntu-Supported-Orientations=portrait`. This will, however, be reset once you reinstall/update the app.

**Comment by patrickjane** [comment]
And sorry for the late response :)

**Comment by gbdomubpkm** [comment]
No problem.
Your manual procedure doesn't seem to work for me. Did you test ?

**Comment by patrickjane** [comment]
No I haven't tried. However this is how I disabled landscape mode before publishing. I was under the assumption it should re-enable landscape mode once removed.

**Comment by patrickjane** [comment]
I have just published the update with scrolling text. Your issue should now be resolved.

**Comment by gbdomubpkm** [comment]
Thanks for the update but the issue doesn't seem to be solved.
![screenshot20220107_144042663](https://user-images.githubusercontent.com/50362604/148552682-5a6f3925-b0cc-4571-ac2c-53fcb16d9130.png)
No scrolling of the tittle

**Comment by patrickjane** [comment]
The screenshot shows the media controls of ubuntu touch. The scrolling text was added to my app. I don't have any possibility to influence what is shown on your screenshot.

**Comment by gbdomubpkm** [comment]
The problem of scrolling the title concerns the smartphone user interface, I think : an issue to open somewhere. There is still the possibility of landscape mode for radio, if you manage to activate it: it would be possible to see the whole title.

**Comment by patrickjane** [comment]
Okay so I am not entirely sure what this has to do with my app? As I said, this is an operating system component, and my app has no effect on it.
When rotated, it would - by the way - still look like this:

![screenshot20220107_171434041](https://user-images.githubusercontent.com/1404715/148573216-8d1cf5e7-fc16-4c34-a3cd-cccb9526221b.png)

But let me repeat: This has nothing to do with my app. To manually enable landscape mode, additionally the file `/opt/click.ubuntu.com/.click/users/phablet/radio.s710/Radio.desktop` needs to be edited (using `sudo`) and the same entry needs to be removed.

But as expected, the app is *not* usable in landscape mode, since I did not design the UI in a way which supports landscape mode. And as stated before, I am not planning to add support for landscape mode, since I find the app is best used in portrait mode, and I am working on other apps currently.

So this is all I can do I'm afraid.

**Comment by gbdomubpkm** [comment]
You are right about the uselessness of the landscape mode to display the whole title on the smartphone. I said something stupid but I was convinced that it was useful in my head !!

And in fact, I was able to test by realizing that after closing your app, it is still possible to play the last station in progress through the sound drop-down menu of the indicator bar of the smartphone!!! Pretty useful function I find 🙂. See :
![screenshot20220108_025050336](https://user-images.githubusercontent.com/50362604/148627894-8d183efb-c18c-4504-9aaf-81676caec212.png)
